# Address and port
address: '0.0.0.0'
port: 8000

# Content directory
dir: '/tmp'

# Basic auth
realm: 'david'

# Users
users:
  user:
    password: '$2a$10$yITzSSNJZAdDZs8iVBQzkuZCzZ49PyjTiPIrmBUKUpB0pwX7eySvW'
    subdir: '/user'
    permissions: crud
  admin:
    password: '$2a$10$yITzSSNJZAdDZs8iVBQzkuZCzZ49PyjTiPIrmBUKUpB0pwX7eySvW'
    permissions: crud

# Logging
log:
  error: true
  create: true
  read: true
  update: true
  delete: true

# CORS
cors:
  origin: '*'