# Address and port
address: '0.0.0.0'
port: 8000

# Content directory
dir: '/tmp'

# Basic auth
realm: 'david'

# Users
users:
  user:
    password: '$2a$10$yITzSSNJZAdDZs8iVBQzkuZCzZ49PyjTiPIrmBUKUpB0pwX7eySvW'
    subdir: '/user'
    permissions: 'crud'
  admin:
    password: '$2a$10$yITzSSNJZAdDZs8iVBQzkuZCzZ49PyjTiPIrmBUKUpB0pwX7eySvW'
    permissions: 'crud'

# Logging
log:
  production: true # All logs will be in NDJSON format. If set to false, than after parsing the config file, the logging mode will be set to TEXT
  debug: true
  error: true
  create: true
  read: true
  update: true
  delete: true

# CORS
cors:
  origin: '*'